# Generated by Django 2.0.4 on 2019-02-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPoolingAssDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='行程唯一id')),
                ('c_userid', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='用户id')),
                ('c_card_owner', models.CharField(max_length=128, verbose_name='车主姓名')),
                ('c_user_phone', models.CharField(max_length=11, verbose_name='车主电话')),
                ('c_start_city', models.CharField(db_index=True, max_length=128, verbose_name='出发城市')),
                ('c_end_city', models.CharField(db_index=True, max_length=128, verbose_name='到达城市')),
                ('t_line', models.TextField(default='', verbose_name='路线')),
                ('d_go_time', models.DateTimeField(db_index=True, verbose_name='出发时间')),
                ('c_bus_type', models.CharField(max_length=128, verbose_name='车型')),
                ('i_vehicle_number', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='该车型荷载')),
                ('i_seat', models.SmallIntegerField(default=0, verbose_name='总共座位')),
                ('i_booked_seat', models.SmallIntegerField(default=0, verbose_name='已预订的座位')),
                ('i_no_booked_seat', models.SmallIntegerField(db_index=True, default=0, verbose_name='剩余座位')),
                ('i_cash', models.IntegerField(default=0, verbose_name='费用')),
                ('t_remark', models.TextField(default='', verbose_name='备注')),
                ('status', models.BooleanField(default=True, help_text='true,false', verbose_name='是否有效')),
            ],
            options={
                'verbose_name_plural': '行程表(中心表)',
                'db_table': 'carpooling_ass_detail',
            },
        ),
        migrations.CreateModel(
            name='CarPoolingCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_fullname', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='城市名')),
                ('c_firstname', models.CharField(db_index=True, max_length=10, verbose_name='首字母(大写)')),
                ('status', models.BooleanField(default=True, help_text='true,false', verbose_name='是否有效')),
            ],
            options={
                'verbose_name_plural': '城市列表',
                'db_table': 'carpooling_city',
            },
        ),
        migrations.CreateModel(
            name='CarPoolingUserConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_userid', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='用户id')),
                ('c_weixin_id', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='微信id')),
                ('c_name', models.CharField(max_length=128, verbose_name='姓名')),
                ('c_phone', models.CharField(max_length=11, verbose_name='电话号码')),
                ('b_phone_status', models.BooleanField(default=False, help_text='true,false', verbose_name='电话号码状态')),
                ('i_cumulative_sum', models.SmallIntegerField(default=10, verbose_name='累积积分')),
                ('status', models.BooleanField(default=True, help_text='true,false', verbose_name='是否有效')),
            ],
            options={
                'verbose_name_plural': '用户表',
                'db_table': 'carpooling_user_conf',
            },
        ),
    ]
