# Generated by Django 2.0.4 on 2019-02-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carPooling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpoolingcity',
            name='c_firstname',
            field=models.CharField(db_index=True, editable=False, max_length=10, verbose_name='首字母(大写)'),
        ),
    ]
