# Generated by Django 2.0.4 on 2019-02-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carPooling', '0002_auto_20190219_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpoolinguserconf',
            name='c_userid',
        ),
    ]
