# Generated by Django 2.0.4 on 2019-02-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carPooling', '0003_remove_carpoolinguserconf_c_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='c_bus_type',
            field=models.CharField(max_length=128, null=True, verbose_name='车型'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='c_card_owner',
            field=models.CharField(max_length=128, null=True, verbose_name='车主姓名'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='c_end_city',
            field=models.CharField(db_index=True, max_length=128, null=True, verbose_name='到达城市'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='c_start_city',
            field=models.CharField(db_index=True, max_length=128, null=True, verbose_name='出发城市'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='c_user_phone',
            field=models.CharField(max_length=11, null=True, verbose_name='车主电话'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='c_userid',
            field=models.CharField(db_index=True, max_length=128, null=True, unique=True, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='d_go_time',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='出发时间'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='i_booked_seat',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='已预订的座位'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='i_cash',
            field=models.IntegerField(default=0, null=True, verbose_name='费用'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='i_no_booked_seat',
            field=models.SmallIntegerField(db_index=True, null=True, verbose_name='剩余座位'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='i_seat',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='总共座位'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='i_vehicle_number',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='该车型荷载'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='t_line',
            field=models.TextField(default='', null=True, verbose_name='路线'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='t_remark',
            field=models.TextField(default='', null=True, verbose_name='备注'),
        ),
    ]
