# Generated by Django 2.0.4 on 2019-02-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carPooling', '0004_auto_20190220_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='c_userid',
            field=models.CharField(db_index=True, max_length=128, null=True, verbose_name='用户id'),
        ),
    ]
