# Generated by Django 2.0.4 on 2019-02-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carPooling', '0005_auto_20190220_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='i_booked_seat',
            field=models.SmallIntegerField(default=0, verbose_name='已预订的座位'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='i_no_booked_seat',
            field=models.SmallIntegerField(db_index=True, verbose_name='剩余座位'),
        ),
    ]
