# Generated by Django 2.0.4 on 2019-02-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carPooling', '0007_auto_20190221_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpoolingassdetail',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='carpoolingassdetail',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间'),
        ),
    ]
