# Generated by Django 2.0.4 on 2019-02-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carPooling', '0008_auto_20190221_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpoolingassdetail',
            name='i_status',
            field=models.SmallIntegerField(help_text='0:取消行程，1:进行中，2：已出发，3：已完成', null=True, verbose_name='行程状态'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='status',
            field=models.BooleanField(default=True, help_text='true,false,用于用户显示', verbose_name='是否删除'),
        ),
    ]
