# Generated by Django 2.0.4 on 2019-02-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carPooling', '0009_auto_20190221_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPoolingRecDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_userid', models.CharField(db_index=True, max_length=128, verbose_name='乘客id')),
                ('c_assid', models.CharField(db_index=True, max_length=128, verbose_name='行程id')),
                ('t_remark', models.TextField(default='', null=True, verbose_name='备注')),
                ('i_booked_seat', models.SmallIntegerField(blank=True, verbose_name='预定座位数')),
                ('c_phone', models.CharField(max_length=11, null=True, verbose_name='电话号码')),
                ('i_status', models.SmallIntegerField(help_text='0:取消行程，1:进行中，2：已出发，3：已完成', verbose_name='行程状态')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('status', models.BooleanField(default=True, help_text='true,false,用于用户显示', verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '乘客行程关联表',
                'db_table': 'carpooling_rec_detail',
            },
        ),
        migrations.AlterUniqueTogether(
            name='carpoolingrecdetail',
            unique_together={('c_assid', 'c_userid')},
        ),
    ]
