# Generated by Django 2.0.4 on 2019-02-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carPooling', '0010_auto_20190222_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpoolingrecdetail',
            name='c_id',
            field=models.CharField(db_index=True, default='aaa', max_length=128, unique=True, verbose_name='行程唯一id'),
            preserve_default=False,
        ),
    ]
