# Generated by Django 2.0.4 on 2019-02-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carPooling', '0011_carpoolingrecdetail_c_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpoolingrecdetail',
            name='c_card_owner',
            field=models.CharField(max_length=128, null=True, verbose_name='车主姓名'),
        ),
        migrations.AddField(
            model_name='carpoolingrecdetail',
            name='c_end_city',
            field=models.CharField(db_index=True, max_length=128, null=True, verbose_name='到达城市'),
        ),
        migrations.AddField(
            model_name='carpoolingrecdetail',
            name='c_start_city',
            field=models.CharField(db_index=True, max_length=128, null=True, verbose_name='出发城市'),
        ),
        migrations.AddField(
            model_name='carpoolingrecdetail',
            name='c_user_phone',
            field=models.CharField(max_length=11, null=True, verbose_name='车主电话'),
        ),
        migrations.AddField(
            model_name='carpoolingrecdetail',
            name='d_go_time',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='出发时间'),
        ),
    ]
