# Generated by Django 2.0.4 on 2019-02-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carPooling', '0012_auto_20190225_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpoolingassdetail',
            name='c_user_phone',
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='c_end_city',
            field=models.CharField(db_index=True, max_length=128, verbose_name='到达城市'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='c_start_city',
            field=models.CharField(db_index=True, max_length=128, verbose_name='出发城市'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='c_userid',
            field=models.CharField(db_index=True, max_length=128, verbose_name='车主id'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='d_go_time',
            field=models.DateTimeField(db_index=True, verbose_name='出发时间'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='i_cash',
            field=models.IntegerField(default=0, verbose_name='费用'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='i_status',
            field=models.SmallIntegerField(help_text='参考CurTripStatus', verbose_name='行程状态'),
        ),
        migrations.AlterField(
            model_name='carpoolingassdetail',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='carpoolingrecdetail',
            name='i_status',
            field=models.SmallIntegerField(help_text='参考CurTripStatus', verbose_name='行程状态'),
        ),
    ]
