# Generated by Django 2.0.4 on 2019-02-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carPooling', '0014_auto_20190226_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpoolingrecdetail',
            name='c_phone',
        ),
        migrations.RemoveField(
            model_name='carpoolingrecdetail',
            name='c_user_phone',
        ),
        migrations.AlterField(
            model_name='carpoolingrecdetail',
            name='c_card_owner',
            field=models.CharField(max_length=128, verbose_name='车主姓名'),
        ),
        migrations.AlterField(
            model_name='carpoolingrecdetail',
            name='c_end_city',
            field=models.CharField(db_index=True, max_length=128, verbose_name='到达城市'),
        ),
        migrations.AlterField(
            model_name='carpoolingrecdetail',
            name='c_start_city',
            field=models.CharField(db_index=True, max_length=128, verbose_name='出发城市'),
        ),
        migrations.AlterField(
            model_name='carpoolingrecdetail',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='carpoolingrecdetail',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
    ]
