# Generated by Django 2.0.4 on 2019-02-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carPooling', '0015_auto_20190226_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpoolingrecdetail',
            name='c_username',
            field=models.CharField(default='aa', max_length=128, verbose_name='乘客姓名'),
            preserve_default=False,
        ),
    ]
