# Generated by Django 2.0.4 on 2019-02-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carPooling', '0016_carpoolingrecdetail_c_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPoolingRecUnbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_recid', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='乘客行程id')),
                ('unsubscribeTags', models.CharField(max_length=128, null=True, verbose_name='乘客取消原因')),
                ('unsubscribeComplain', models.CharField(max_length=128, null=True, verbose_name='投诉原因')),
            ],
            options={
                'verbose_name_plural': '乘客退订详情统计表',
                'db_table': 'carpooling_rec_unbook',
            },
        ),
    ]
