# Generated by Django 2.0.4 on 2019-05-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carPooling', '0017_carpoolingrecunbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpoolinguserconf',
            name='c_name',
            field=models.CharField(max_length=128, null=True, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='carpoolinguserconf',
            name='c_phone',
            field=models.CharField(db_index=True, max_length=11, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='carpoolinguserconf',
            name='c_weixin_id',
            field=models.CharField(db_index=True, max_length=128, null=True, verbose_name='微信id'),
        ),
    ]
