# Generated by Django 2.0.4 on 2019-05-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carPooling', '0018_auto_20190521_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpoolinguserconf',
            name='c_weixin_id',
        ),
        migrations.AddField(
            model_name='carpoolinguserconf',
            name='w_city',
            field=models.CharField(max_length=128, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='carpoolinguserconf',
            name='w_country',
            field=models.CharField(max_length=128, null=True, verbose_name='国家'),
        ),
        migrations.AddField(
            model_name='carpoolinguserconf',
            name='w_headimgurl',
            field=models.CharField(help_text='用户没有头像时该项为空。若用户更换头像，原有头像URL将失效。', max_length=256, null=True, verbose_name='用户头像'),
        ),
        migrations.AddField(
            model_name='carpoolinguserconf',
            name='w_nickname',
            field=models.CharField(max_length=128, null=True, verbose_name='用户昵称'),
        ),
        migrations.AddField(
            model_name='carpoolinguserconf',
            name='w_openid',
            field=models.CharField(db_index=True, default=None, help_text='微信用户的唯一标识', max_length=128, verbose_name='微信id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carpoolinguserconf',
            name='w_province',
            field=models.CharField(max_length=128, null=True, verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='carpoolinguserconf',
            name='w_sex',
            field=models.SmallIntegerField(help_text='值为1时是男性，值为2时是女性，值为0时是未知', null=True, verbose_name='用户的性别'),
        ),
        migrations.AlterField(
            model_name='carpoolinguserconf',
            name='c_phone',
            field=models.CharField(db_index=True, max_length=11, null=True, verbose_name='电话号码'),
        ),
    ]
